### ISSUE TITLE
a bug？

### ISSUE THREAD

**Issue by Crimson-pro** [zliucr/coach#5]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [800, 400]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by luoqiaoyang** [comment]
Hi, I got the same problem by running it on Python 3.6 and PyTorch 1.7.1 version. How did you solve that?

**Comment by Crimson-pro** [comment]
The author performed 'loss.backward()' twice, and I modified the code to perform 'loss.backward()' only once. I think this is a problem with pytorch, this code should have no problem running on colab？

**Comment by luoqiaoyang** [comment]
In the `./src/slu/trainer.py`, there are several different backward() function with retain_graph=True. Which one did you modified? In this training file, the model is updated in the first for loop (line 63-69) multiple times by `self.optimizer.step()`. In my view, the model might only need to be updated once here by average all sample loss and use `self.optimizer.step()` outside for loop. I am not sure if I understand correctly.

**Comment by rollben** [comment]
hi Crimson-pro，
how did you solve the problem?
